export const data = [
    {
        name: "Mango-Type6728",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 4,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type134234",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 5,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: false,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type21",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 2.5,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type7",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 2,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type3",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 3.5,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        longDisc: 'This mangoes are most famous among all the individuals who looks for a sweet taste from mangoes. These will provide a hight level sweetness.',
        instock: false,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type653",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 5,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type132",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 4,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type23",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 4.2,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type3134",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 3,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: false,
        countInStock: 5,
        numReviews: 12
    },
    {
        name: "Mango-Type234",
        type: 'Normal',
        category: 'Abc',
        image: 'https://freesvg.org/img/manggo.png',
        rating: 4.5,
        cost: 80,
        description: 'May be the best mangoes lying around the city in this season',
        instock: true,
        countInStock: 5,
        numReviews: 12
    },
]
